[package]
name    = "bytesense-core"
version = "1.0.0"
edition = "2021"
rust-version = "1.88"

[lib]
name       = "bytesense_rust_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.2", features = ["abi3-py39"] }

[profile.release]
opt-level     = 3
lto           = true
codegen-units = 1
panic         = "abort"
strip         = true
