"""Evaluate a frozen, untrained multilingual transfer corpus using exact Unicode.

Inputs are translations of one document, not independent real-world samples.
Only generated bytes and reference hashes are used; source text is not copied
into reports or the package. No model training or parameter selection happens
here. Unrepresentable codec/document combinations are reported, never repaired.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import platform
import subprocess
import time
import unicodedata
import xml.etree.ElementTree as ET
from pathlib import Path

from evaluate_corpus import engines

SOURCE = "https://github.com/unicode-org/udhr"
COMMIT = "588b3f4b2d0467aff54842a4b926551b69d5a66a"
DOCUMENTS = {
    "eng": ["cp1252", "cp437", "cp850"],
    "tur": ["cp1254", "iso8859_9", "cp857"],
    "fra": ["cp1252", "iso8859_15", "cp850"],
    "deu_1996": ["cp1252", "iso8859_15", "cp850"],
    "spa": ["cp1252", "iso8859_15", "cp850"],
    "por_PT": ["cp1252", "cp860"],
    "ita": ["cp1252", "iso8859_15", "cp850"],
    "nld": ["cp1252", "cp850"],
    "dan": ["cp1252", "cp865"],
    "nob": ["cp1252", "cp865"],
    "swe": ["cp1252", "cp850"],
    "fin": ["cp1252", "cp850"],
    "isl": ["cp1252", "cp861"],
    "ces": ["cp1250", "iso8859_2", "cp852"],
    "pol": ["cp1250", "iso8859_2", "cp852"],
    "hun": ["cp1250", "iso8859_2", "cp852"],
    "ron_2006": ["iso8859_16"],
    "rus": ["cp1251", "koi8_r", "cp866"],
    "ukr": ["cp1251", "koi8_u", "cp1125"],
    "ell_monotonic": ["cp1253", "iso8859_7", "cp737"],
    "heb": ["cp1255", "iso8859_8"],
    "arb": ["cp1256", "iso8859_6"],
    "tha": ["cp874", "tis_620"],
    "vie": ["cp1258"],
    "jpn": ["shift_jis", "euc_jp", "iso2022_jp"],
    "kor": ["euc_kr", "cp949", "iso2022_kr"],
    "cmn_hans": ["gb2312", "gb18030", "hz"],
    "cmn_hant": ["big5", "big5hkscs"],
}
# Explicit fixture preparation, not a detector or data-repair operation.
# Unicode punctuation has no representation in several historical code pages.
PUNCTUATION = str.maketrans(
    {"\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"', "\u2013": "-", "\u2014": "-"}
)


def cases(corpus: Path) -> tuple[list[tuple[dict, bytes, str]], list[dict]]:
    actual = subprocess.check_output(
        ["git", "-C", str(corpus), "rev-parse", "HEAD"], text=True
    ).strip()
    if actual != COMMIT:
        raise ValueError(f"Expected corpus commit {COMMIT}, got {actual}")
    subprocess.run(
        ["git", "-C", str(corpus), "diff", "--quiet", COMMIT, "--", "data/udhr"], check=True
    )
    rows, excluded = [], []
    for document, codecs in DOCUMENTS.items():
        path = corpus / "data" / "udhr" / f"udhr_{document}.xml"
        raw = path.read_bytes()
        root = ET.fromstring(raw)
        text = unicodedata.normalize("NFC", " ".join("".join(root.itertext()).split()))
        text = text.translate(PUNCTUATION)
        for length in (64, 512, None):
            reference = text[:length]
            for codec in ["utf_8", "utf_16_le", "utf_16_be", *codecs]:
                item = {
                    "document": document,
                    "source_sha256": hashlib.sha256(raw).hexdigest(),
                    "length": length,
                    "characters": len(reference),
                    "reference_sha256": hashlib.sha256(reference.encode()).hexdigest(),
                    "encoding": codec,
                    "family": "unicode" if codec.startswith("utf_") else "legacy",
                }
                try:
                    data = reference.encode(codec, errors="strict")
                except UnicodeError as exc:
                    excluded.append(dict(item, reason=str(exc)))
                    continue
                if data.decode(codec, errors="strict") != reference:
                    excluded.append(dict(item, reason="codec does not round-trip exact Unicode"))
                    continue
                rows.append(
                    (
                        dict(item, sha256=hashlib.sha256(data).hexdigest(), bytes=len(data)),
                        data,
                        reference,
                    )
                )
    return rows, excluded


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("corpus", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--inventory-only", action="store_true")
    parser.add_argument(
        "--engine",
        action="append",
        choices=["bytesense", "chardet", "charset-normalizer", "chardetng-py"],
    )
    args = parser.parse_args()
    selected, excluded = cases(args.corpus)
    detectors = (
        {}
        if args.inventory_only
        else engines(args.engine or ["bytesense", "chardet", "charset-normalizer", "chardetng-py"])
    )
    records = []
    for item, data, reference in selected:
        record = dict(item, results={})
        for name, detect in detectors.items():
            started = time.perf_counter()
            try:
                encoding = detect(data)
                elapsed = time.perf_counter() - started
                correct = bool(encoding and data.decode(encoding, errors="strict") == reference)
                record["results"][name] = dict(encoding=encoding, correct=correct, seconds=elapsed)
            except Exception as exc:
                record["results"][name] = dict(error=repr(exc), correct=False)
        records.append(record)
    summary = {
        name: {
            family: {
                "correct": sum(
                    r["results"][name]["correct"]
                    for r in records
                    if family == "all" or r["family"] == family
                ),
                "total": sum(family == "all" or r["family"] == family for r in records),
            }
            for family in ("all", "legacy", "unicode")
        }
        for name in detectors
    }
    report = {
        "source": SOURCE,
        "commit": COMMIT,
        "documents": len(DOCUMENTS),
        "python": platform.python_version(),
        "platform": platform.platform(),
        "versions": {name: importlib.metadata.version(name) for name in detectors},
        "notes": "Untrained transfer set; translations of one document, not independent observations. NFC, collapsed whitespace and explicit ASCII punctuation mapping; 64/512/full character variants. Strictly encodable, round-tripping cases only; every exclusion is recorded.",
        "summary": summary,
        "excluded": excluded,
        "records": records,
    }
    args.output.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(
        json.dumps({"cases": len(records), "excluded": len(excluded), "summary": summary}, indent=2)
    )


if __name__ == "__main__":
    main()
